  # ──────────────────────────────────────────────────────────
  # KONFIGURACJA PINÓW - ESP32-C3 SuperMini
  # ──────────────────────────────────────────────────────────
  #
  #  Lewa kolumna (header)   |   Prawa kolumna (header)
  #  GPIO5  FSPIWP, MISO     |   5V
  #  GPIO6  SPI FLASH – NIE UŻYWAĆ |   GND
  #  GPIO7  SPI FLASH – NIE UŻYWAĆ |   3.3V
  #  GPIO8  BUILTIN LED      |   GPIO4  SDA I2C, ADC1_4
  #  GPIO9  encoder DT (pull-up!)  |   GPIO3  encoder SW
  #  GPIO10 encoder CLK      |   GPIO2  FSPIQ, BOOT, ADC1_2
  #  GPIO20 TXD0             |   GPIO1  ADC1_1
  #  GPIO21 RXD0             |   GPIO0  ADC1_0
  #
  # ──────────────────────────────────────────────────────────
  # ============================================================
# TagTuner UID-Only for ESP32-C3 SuperMini (POPRAWIONY)
# ============================================================

substitutions:
  name: "tagtuner-c3"
  friendly_name: "TagTuner C3"

  # ───────── PINY – GRUPOWANIE STRONAMI ─────────
  # LEWA STRONA PŁYTKI → PN532 (I2C)
  pin_i2c_sda: "4"     # GPIO4
  pin_i2c_scl: "5"     # GPIO5

  # ENKODER – GPIO9/10 (9=strapping, OK z pull-up; NIE używać 6/7 = SPI Flash!)
  pin_encoder_clk: "10"  # GPIO10
  pin_encoder_dt: "9"    # GPIO9 (pull-up wewn. lub w enkoderze)
  pin_encoder_sw: "3"    # GPIO3

  # LED
  pin_led: "8"        # GPIO8 (built-in LED, active LOW)

# ============================================================

esphome:
  name: "${name}"
  friendly_name: ${friendly_name}
  min_version: 2024.1.0
  name_add_mac_suffix: true

  on_boot:
    priority: -100
    then:
      - light.turn_on:
          id: led1
          flash_length: 500ms
      - wait_until:
          condition:
            api.connected:
          timeout: 20s
      - text_sensor.template.publish:
          id: status
          state: "Ready"

esp32:
  board: esp32-c3-devkitm-1
  framework:
    type: arduino   # <<< KLUCZOWE (Improv działa tylko na Arduino)

logger:
  level: DEBUG

# ============================================================
# KOMUNIKACJA
# ============================================================

i2c:
  id: bus_i2c
  sda: ${pin_i2c_sda}
  scl: ${pin_i2c_scl}
  scan: false
  frequency: 100kHz

api:
  encryption:
    key: "30sHFNxlCElAfv41LY9yQlPgOS3rKLfjR150gcPuLXo="

ota:
  - platform: esphome
    password: "dc5897bdc4d59854c65db6723d62105a"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  manual_ip:
    static_ip: 192.168.0.41
    gateway: 192.168.0.1
    subnet: 255.255.255.0
  ap:
    ssid: "Czytnikkart Fallback"
    password: "GVr80y9d6ODu"

captive_portal:

improv_serial:

esp32_improv:
  authorizer: toggle

# ============================================================
# WEJŚCIA
# ============================================================

binary_sensor:
  - platform: gpio
    id: toggle
    pin:
      number: ${pin_encoder_sw}
      inverted: true
      mode:
        input: true
        pullup: true
    on_multi_click:
      - timing:
          - ON for at most 1s
          - OFF for at most 0.25s
          - ON for at most 1s
          - OFF for at most 0.25s
          - ON for at most 1s
        then:
          - script.execute: led_blink
          - homeassistant.event:
              event: esphome.tagtuner_button
              data:
                action: "triple"

      - timing:
          - ON for at most 1s
          - OFF for at most 0.25s
          - ON for at most 1s
          - OFF for at least 0.25s
        then:
          - script.execute: led_blink
          - homeassistant.event:
              event: esphome.tagtuner_button
              data:
                action: "double"

      - timing:
          - ON for 0.5s to 2s
          - OFF for at least 50ms
        then:
          - script.execute: led_blink
          - homeassistant.event:
              event: esphome.tagtuner_button
              data:
                action: "long"

      - timing:
          - ON for at most 0.5s
          - OFF for at least 260ms
        then:
          - script.execute: led_blink
          - homeassistant.event:
              event: esphome.tagtuner_button
              data:
                action: "single"

  - platform: template
    name: "Tag Present"
    id: is_tag
    device_class: occupancy

# ============================================================
# LED
# ============================================================

output:
  - platform: gpio
    pin: ${pin_led}
    inverted: true
    id: led1_gpio

light:
  - platform: binary
    id: led1
    output: led1_gpio
    restore_mode: ALWAYS_OFF

# ============================================================
# SKRYPTY
# ============================================================

script:
  - id: led_blink
    then:
      - light.turn_on:
          id: led1
          flash_length: 100ms

  - id: led_blink_success
    then:
      - light.turn_on:
          id: led1
          flash_length: 120ms
      - delay: 80ms
      - light.turn_on:
          id: led1
          flash_length: 120ms

  - id: led_blink_error
    then:
      - light.turn_on:
          id: led1
          flash_length: 60ms
      - delay: 70ms
      - light.turn_on:
          id: led1
          flash_length: 60ms
      - delay: 70ms
      - light.turn_on:
          id: led1
          flash_length: 60ms

# ============================================================
# ENKODER
# ============================================================

sensor:
  - platform: rotary_encoder
    id: rotary
    pin_a: ${pin_encoder_clk}
    pin_b: ${pin_encoder_dt}
    resolution: 2
    restore_mode: ALWAYS_ZERO
    on_clockwise:
      - homeassistant.event:
          event: esphome.tagtuner_volume
          data:
            action: "up"
      - script.execute: led_blink
    on_anticlockwise:
      - homeassistant.event:
          event: esphome.tagtuner_volume
          data:
            action: "down"
      - script.execute: led_blink

# ============================================================
# DIAGNOSTYKA
# ============================================================

text_sensor:
  - platform: template
    id: status
    name: "Status"
    icon: mdi:ladybug
    entity_category: DIAGNOSTIC

button:
  - platform: restart
    name: "Restart"
    entity_category: DIAGNOSTIC

# ============================================================
# PN532 NFC
# ============================================================

pn532_i2c:
  - id: pn532_board
    i2c_id: bus_i2c
    update_interval: 350ms

    on_tag_removed:
      - binary_sensor.template.publish:
          id: is_tag
          state: false
      - text_sensor.template.publish:
          id: status
          state: "Tag removed"
      - script.execute: led_blink

    on_tag:
      - binary_sensor.template.publish:
          id: is_tag
          state: true
      - text_sensor.template.publish:
          id: status
          state: !lambda 'return "Tag: " + x;'
      - if:
          condition:
            lambda: 'return x.size() >= 8;'
          then:
            - homeassistant.tag_scanned: !lambda 'return x;'
            - script.execute: led_blink_success
          else:
            - script.execute: led_blink_error